### ISSUE TITLE
Could you share the original news articles parallel corpus?

### ISSUE THREAD

**Issue by sobir-git** [stibiumghost/tajik-to-persian-transliteration#1]
Currently working on a similar task but with CNN models. 
I noticed some errors in the news dataset. I am applying character alignment algorithm which can result in better text splitting. Would be much appreciated.

**Comment by stibiumghost** [comment]
Look in [training_data/unsorted_data](https://github.com/stibiumghost/tajik-to-persian-transliteration/tree/main/training_data/unsorted_data)
Does it fulfill your request? I'm afraid I don't have full articles.

**Comment by sobir-git** [comment]
Thanks for providing this data! Sure it helps a lot .👍
